springdoc:
  swagger-ui:
    enabled: false

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI}

marketplace:
  security:
    enabled: true

management:
  endpoint:
    health:
      show-details: never
  tracing:
    sampling:
      probability: 0.1

logging:
  level:
    root: WARN
    com.enterprise.marketplace: INFO
