springdoc:
  swagger-ui:
    enabled: true

marketplace:
  security:
    enabled: ${MARKETPLACE_SECURITY_ENABLED:false}

logging:
  level:
    com.enterprise.marketplace: DEBUG

management:
  endpoint:
    health:
      show-details: always
