springdoc:
  swagger-ui:
    enabled: false

marketplace:
  ollama:
    base-url: ${OLLAMA_BASE_URL}

management:
  endpoint:
    health:
      show-details: never
  tracing:
    sampling:
      probability: 0.1

logging:
  level:
    root: WARN
    com.enterprise.marketplace: INFO
