spring:
  elasticsearch:
    uris: ${ELASTICSEARCH_URIS:http://localhost:9200}

springdoc:
  swagger-ui:
    enabled: true

marketplace:
  elasticsearch:
    enabled: true

logging:
  level:
    com.enterprise.marketplace: DEBUG

management:
  endpoint:
    health:
      show-details: always
      group:
        readiness:
          include: readinessState,ping,elasticsearch
