spring:
  elasticsearch:
    uris: ${ELASTICSEARCH_URIS}

marketplace:
  elasticsearch:
    enabled: true

management:
  endpoint:
    health:
      show-details: when_authorized
      group:
        readiness:
          include: readinessState,ping,elasticsearch
  tracing:
    sampling:
      probability: 0.5
